#!/usr/bin/env python3
"""
Rüya tabirleri veri toplama scripti
500+ rüya objesi ve 50+ eylem
"""

import json
from pathlib import Path

class DataCollector:
    def __init__(self):
        self.data_dir = Path("data/raw")
        self.data_dir.mkdir(parents=True, exist_ok=True)

    def generate_objects(self):
        """Temel rüya objelerini oluştur - 200+ obje"""

        objects = [
            # HAYVANLAR (50+)
            {"id": "yilan", "name": "Yılan", "category": "hayvanlar", "keywords": ["yılan", "kobra", "engerek"], "search_volume": "high"},
            {"id": "kopek", "name": "Köpek", "category": "hayvanlar", "keywords": ["köpek", "it", "köpek yavrusu"], "search_volume": "high"},
            {"id": "kedi", "name": "Kedi", "category": "hayvanlar", "keywords": ["kedi", "kedicik", "yavru kedi"], "search_volume": "high"},
            {"id": "at", "name": "At", "category": "hayvanlar", "keywords": ["at", "tay", "aygır", "kısrak"], "search_volume": "high"},
            {"id": "kus", "name": "Kuş", "category": "hayvanlar", "keywords": ["kuş", "serçe", "bülbül"], "search_volume": "high"},
            {"id": "balik", "name": "Balık", "category": "hayvanlar", "keywords": ["balık", "balıklar"], "search_volume": "high"},
            {"id": "aslan", "name": "Aslan", "category": "hayvanlar", "keywords": ["aslan", "dişi aslan"], "search_volume": "medium"},
            {"id": "kaplan", "name": "Kaplan", "category": "hayvanlar", "keywords": ["kaplan"], "search_volume": "medium"},
            {"id": "fare", "name": "Fare", "category": "hayvanlar", "keywords": ["fare", "sıçan"], "search_volume": "high"},
            {"id": "orumcek", "name": "Örümcek", "category": "hayvanlar", "keywords": ["örümcek", "tarantula"], "search_volume": "high"},
            {"id": "ari", "name": "Arı", "category": "hayvanlar", "keywords": ["arı", "bal arısı", "eşek arısı"], "search_volume": "medium"},
            {"id": "kelebek", "name": "Kelebek", "category": "hayvanlar", "keywords": ["kelebek"], "search_volume": "medium"},
            {"id": "karinca", "name": "Karınca", "category": "hayvanlar", "keywords": ["karınca"], "search_volume": "medium"},
            {"id": "kurt", "name": "Kurt", "category": "hayvanlar", "keywords": ["kurt", "bozkurt"], "search_volume": "medium"},
            {"id": "ayi", "name": "Ayı", "category": "hayvanlar", "keywords": ["ayı"], "search_volume": "medium"},
            {"id": "fil", "name": "Fil", "category": "hayvanlar", "keywords": ["fil"], "search_volume": "medium"},
            {"id": "maymun", "name": "Maymun", "category": "hayvanlar", "keywords": ["maymun", "goril"], "search_volume": "medium"},
            {"id": "tavsan", "name": "Tavşan", "category": "hayvanlar", "keywords": ["tavşan"], "search_volume": "medium"},
            {"id": "koyun", "name": "Koyun", "category": "hayvanlar", "keywords": ["koyun", "kuzu"], "search_volume": "medium"},
            {"id": "keci", "name": "Keçi", "category": "hayvanlar", "keywords": ["keçi", "oğlak"], "search_volume": "medium"},
            {"id": "inek", "name": "İnek", "category": "hayvanlar", "keywords": ["inek", "buzağı"], "search_volume": "medium"},
            {"id": "deve", "name": "Deve", "category": "hayvanlar", "keywords": ["deve"], "search_volume": "low"},
            {"id": "esek", "name": "Eşek", "category": "hayvanlar", "keywords": ["eşek", "merkep"], "search_volume": "low"},
            {"id": "horoz", "name": "Horoz", "category": "hayvanlar", "keywords": ["horoz"], "search_volume": "medium"},
            {"id": "tavuk", "name": "Tavuk", "category": "hayvanlar", "keywords": ["tavuk", "civciv"], "search_volume": "medium"},
            {"id": "kartal", "name": "Kartal", "category": "hayvanlar", "keywords": ["kartal"], "search_volume": "medium"},
            {"id": "guvercin", "name": "Güvercin", "category": "hayvanlar", "keywords": ["güvercin", "kumru"], "search_volume": "medium"},
            {"id": "karga", "name": "Karga", "category": "hayvanlar", "keywords": ["karga"], "search_volume": "medium"},
            {"id": "baykus", "name": "Baykuş", "category": "hayvanlar", "keywords": ["baykuş", "puhu"], "search_volume": "medium"},
            {"id": "timsah", "name": "Timsah", "category": "hayvanlar", "keywords": ["timsah"], "search_volume": "low"},
            {"id": "kaplumbaga", "name": "Kaplumbağa", "category": "hayvanlar", "keywords": ["kaplumbağa"], "search_volume": "medium"},
            {"id": "akrep", "name": "Akrep", "category": "hayvanlar", "keywords": ["akrep"], "search_volume": "high"},
            {"id": "kertenkele", "name": "Kertenkele", "category": "hayvanlar", "keywords": ["kertenkele"], "search_volume": "low"},
            {"id": "kurbaga", "name": "Kurbağa", "category": "hayvanlar", "keywords": ["kurbağa"], "search_volume": "medium"},
            {"id": "yunus", "name": "Yunus", "category": "hayvanlar", "keywords": ["yunus", "yunus balığı"], "search_volume": "medium"},
            {"id": "kopekbaligi", "name": "Köpekbalığı", "category": "hayvanlar", "keywords": ["köpekbalığı"], "search_volume": "medium"},
            {"id": "bocek", "name": "Böcek", "category": "hayvanlar", "keywords": ["böcek", "hamam böceği"], "search_volume": "medium"},
            {"id": "solucan", "name": "Solucan", "category": "hayvanlar", "keywords": ["solucan"], "search_volume": "low"},
            {"id": "bit", "name": "Bit", "category": "hayvanlar", "keywords": ["bit", "sirke"], "search_volume": "medium"},
            {"id": "pire", "name": "Pire", "category": "hayvanlar", "keywords": ["pire"], "search_volume": "low"},
            {"id": "domuz", "name": "Domuz", "category": "hayvanlar", "keywords": ["domuz"], "search_volume": "medium"},
            {"id": "tilki", "name": "Tilki", "category": "hayvanlar", "keywords": ["tilki"], "search_volume": "medium"},
            {"id": "ceylan", "name": "Ceylan", "category": "hayvanlar", "keywords": ["ceylan", "geyik"], "search_volume": "low"},
            {"id": "sincap", "name": "Sincap", "category": "hayvanlar", "keywords": ["sincap"], "search_volume": "low"},
            {"id": "kirpi", "name": "Kirpi", "category": "hayvanlar", "keywords": ["kirpi"], "search_volume": "low"},
            {"id": "yarasa", "name": "Yarasa", "category": "hayvanlar", "keywords": ["yarasa"], "search_volume": "medium"},
            {"id": "penguen", "name": "Penguen", "category": "hayvanlar", "keywords": ["penguen"], "search_volume": "low"},
            {"id": "zurafa", "name": "Zürafa", "category": "hayvanlar", "keywords": ["zürafa"], "search_volume": "low"},
            {"id": "zebra", "name": "Zebra", "category": "hayvanlar", "keywords": ["zebra"], "search_volume": "low"},
            {"id": "gergedan", "name": "Gergedan", "category": "hayvanlar", "keywords": ["gergedan"], "search_volume": "low"},

            # İNSANLAR (35+)
            {"id": "anne", "name": "Anne", "category": "insanlar", "keywords": ["anne", "annem", "ana"], "search_volume": "high"},
            {"id": "baba", "name": "Baba", "category": "insanlar", "keywords": ["baba", "babam"], "search_volume": "high"},
            {"id": "kardes", "name": "Kardeş", "category": "insanlar", "keywords": ["kardeş", "abi", "abla"], "search_volume": "high"},
            {"id": "es", "name": "Eş", "category": "insanlar", "keywords": ["eş", "koca", "karı", "eşim"], "search_volume": "high"},
            {"id": "cocuk", "name": "Çocuk", "category": "insanlar", "keywords": ["çocuk", "oğul", "kız"], "search_volume": "high"},
            {"id": "bebek", "name": "Bebek", "category": "insanlar", "keywords": ["bebek", "yeni doğan"], "search_volume": "high"},
            {"id": "olu", "name": "Ölü", "category": "insanlar", "keywords": ["ölü", "ölmüş", "merhum", "vefat etmiş"], "search_volume": "high"},
            {"id": "olu_anne", "name": "Ölmüş Anne", "category": "insanlar", "keywords": ["ölmüş anne", "vefat etmiş anne"], "search_volume": "high"},
            {"id": "olu_baba", "name": "Ölmüş Baba", "category": "insanlar", "keywords": ["ölmüş baba", "vefat etmiş baba"], "search_volume": "high"},
            {"id": "tanimadik_biri", "name": "Tanımadık Biri", "category": "insanlar", "keywords": ["tanımadık", "yabancı"], "search_volume": "medium"},
            {"id": "dusman", "name": "Düşman", "category": "insanlar", "keywords": ["düşman", "hasım"], "search_volume": "medium"},
            {"id": "arkadas", "name": "Arkadaş", "category": "insanlar", "keywords": ["arkadaş", "dost"], "search_volume": "high"},
            {"id": "sevgili", "name": "Sevgili", "category": "insanlar", "keywords": ["sevgili", "aşk"], "search_volume": "high"},
            {"id": "eski_sevgili", "name": "Eski Sevgili", "category": "insanlar", "keywords": ["eski sevgili", "manita"], "search_volume": "high"},
            {"id": "dede", "name": "Dede", "category": "insanlar", "keywords": ["dede", "büyükbaba"], "search_volume": "medium"},
            {"id": "nine", "name": "Nine", "category": "insanlar", "keywords": ["nine", "babaanne", "anneanne"], "search_volume": "medium"},
            {"id": "amca", "name": "Amca", "category": "insanlar", "keywords": ["amca"], "search_volume": "low"},
            {"id": "dayi", "name": "Dayı", "category": "insanlar", "keywords": ["dayı"], "search_volume": "low"},
            {"id": "hala", "name": "Hala", "category": "insanlar", "keywords": ["hala"], "search_volume": "low"},
            {"id": "teyze", "name": "Teyze", "category": "insanlar", "keywords": ["teyze"], "search_volume": "low"},
            {"id": "komsu", "name": "Komşu", "category": "insanlar", "keywords": ["komşu"], "search_volume": "low"},
            {"id": "ogretmen", "name": "Öğretmen", "category": "insanlar", "keywords": ["öğretmen", "hoca"], "search_volume": "medium"},
            {"id": "doktor", "name": "Doktor", "category": "insanlar", "keywords": ["doktor", "hekim"], "search_volume": "medium"},
            {"id": "polis", "name": "Polis", "category": "insanlar", "keywords": ["polis"], "search_volume": "medium"},
            {"id": "asker", "name": "Asker", "category": "insanlar", "keywords": ["asker"], "search_volume": "medium"},
            {"id": "imam", "name": "İmam", "category": "insanlar", "keywords": ["imam", "hoca"], "search_volume": "medium"},
            {"id": "padisah", "name": "Padişah", "category": "insanlar", "keywords": ["padişah", "sultan"], "search_volume": "low"},
            {"id": "kral", "name": "Kral", "category": "insanlar", "keywords": ["kral", "kraliçe"], "search_volume": "low"},
            {"id": "hirsiz", "name": "Hırsız", "category": "insanlar", "keywords": ["hırsız"], "search_volume": "medium"},
            {"id": "gelin", "name": "Gelin", "category": "insanlar", "keywords": ["gelin"], "search_volume": "medium"},
            {"id": "damat", "name": "Damat", "category": "insanlar", "keywords": ["damat"], "search_volume": "medium"},
            {"id": "hamile_kadin", "name": "Hamile Kadın", "category": "insanlar", "keywords": ["hamile", "gebe"], "search_volume": "high"},
            {"id": "kiz_cocugu", "name": "Kız Çocuğu", "category": "insanlar", "keywords": ["kız çocuğu", "kız bebek"], "search_volume": "medium"},
            {"id": "erkek_cocugu", "name": "Erkek Çocuğu", "category": "insanlar", "keywords": ["erkek çocuğu", "oğlan"], "search_volume": "medium"},
            {"id": "yasli", "name": "Yaşlı", "category": "insanlar", "keywords": ["yaşlı", "ihtiyar"], "search_volume": "medium"},

            # DOĞAL ELEMENTLER (35+)
            {"id": "su", "name": "Su", "category": "doga", "keywords": ["su", "sular"], "search_volume": "high"},
            {"id": "ates", "name": "Ateş", "category": "doga", "keywords": ["ateş", "alev", "yangın"], "search_volume": "high"},
            {"id": "toprak", "name": "Toprak", "category": "doga", "keywords": ["toprak"], "search_volume": "medium"},
            {"id": "hava", "name": "Hava", "category": "doga", "keywords": ["hava", "rüzgar", "fırtına"], "search_volume": "medium"},
            {"id": "gunes", "name": "Güneş", "category": "doga", "keywords": ["güneş"], "search_volume": "medium"},
            {"id": "ay", "name": "Ay", "category": "doga", "keywords": ["ay", "dolunay", "hilal"], "search_volume": "high"},
            {"id": "yildiz", "name": "Yıldız", "category": "doga", "keywords": ["yıldız", "yıldızlar"], "search_volume": "medium"},
            {"id": "bulut", "name": "Bulut", "category": "doga", "keywords": ["bulut"], "search_volume": "low"},
            {"id": "yagmur", "name": "Yağmur", "category": "doga", "keywords": ["yağmur"], "search_volume": "high"},
            {"id": "kar", "name": "Kar", "category": "doga", "keywords": ["kar"], "search_volume": "high"},
            {"id": "dolu", "name": "Dolu", "category": "doga", "keywords": ["dolu"], "search_volume": "low"},
            {"id": "simsek", "name": "Şimşek", "category": "doga", "keywords": ["şimşek", "yıldırım"], "search_volume": "medium"},
            {"id": "gokkusagi", "name": "Gökkuşağı", "category": "doga", "keywords": ["gökkuşağı"], "search_volume": "medium"},
            {"id": "deniz", "name": "Deniz", "category": "doga", "keywords": ["deniz"], "search_volume": "high"},
            {"id": "okyanus", "name": "Okyanus", "category": "doga", "keywords": ["okyanus"], "search_volume": "low"},
            {"id": "nehir", "name": "Nehir", "category": "doga", "keywords": ["nehir", "ırmak", "çay", "dere"], "search_volume": "medium"},
            {"id": "gol", "name": "Göl", "category": "doga", "keywords": ["göl"], "search_volume": "medium"},
            {"id": "dag", "name": "Dağ", "category": "doga", "keywords": ["dağ", "dağlar"], "search_volume": "medium"},
            {"id": "orman", "name": "Orman", "category": "doga", "keywords": ["orman", "ağaçlık"], "search_volume": "medium"},
            {"id": "col", "name": "Çöl", "category": "doga", "keywords": ["çöl"], "search_volume": "low"},
            {"id": "magara", "name": "Mağara", "category": "doga", "keywords": ["mağara"], "search_volume": "medium"},
            {"id": "deprem", "name": "Deprem", "category": "doga", "keywords": ["deprem", "zelzele"], "search_volume": "high"},
            {"id": "sel", "name": "Sel", "category": "doga", "keywords": ["sel", "sel baskını"], "search_volume": "medium"},
            {"id": "volkan", "name": "Volkan", "category": "doga", "keywords": ["volkan", "yanardağ"], "search_volume": "low"},
            {"id": "cicek", "name": "Çiçek", "category": "doga", "keywords": ["çiçek", "gül", "papatya"], "search_volume": "medium"},
            {"id": "gul", "name": "Gül", "category": "doga", "keywords": ["gül", "kırmızı gül"], "search_volume": "medium"},
            {"id": "agac", "name": "Ağaç", "category": "doga", "keywords": ["ağaç"], "search_volume": "medium"},
            {"id": "yaprak", "name": "Yaprak", "category": "doga", "keywords": ["yaprak"], "search_volume": "low"},
            {"id": "cimen", "name": "Çimen", "category": "doga", "keywords": ["çimen", "yeşillik"], "search_volume": "low"},
            {"id": "tas", "name": "Taş", "category": "doga", "keywords": ["taş", "kaya"], "search_volume": "medium"},
            {"id": "kum", "name": "Kum", "category": "doga", "keywords": ["kum", "kumsal"], "search_volume": "low"},
            {"id": "camur", "name": "Çamur", "category": "doga", "keywords": ["çamur", "balçık"], "search_volume": "medium"},
            {"id": "dalga", "name": "Dalga", "category": "doga", "keywords": ["dalga", "deniz dalgası"], "search_volume": "medium"},
            {"id": "tsunami", "name": "Tsunami", "category": "doga", "keywords": ["tsunami", "dev dalga"], "search_volume": "medium"},
            {"id": "buz", "name": "Buz", "category": "doga", "keywords": ["buz"], "search_volume": "low"},

            # MEKANLAR (30+)
            {"id": "ev", "name": "Ev", "category": "mekanlar", "keywords": ["ev", "konut", "yuva"], "search_volume": "high"},
            {"id": "eski_ev", "name": "Eski Ev", "category": "mekanlar", "keywords": ["eski ev", "çocukluk evi"], "search_volume": "medium"},
            {"id": "oda", "name": "Oda", "category": "mekanlar", "keywords": ["oda"], "search_volume": "medium"},
            {"id": "mutfak", "name": "Mutfak", "category": "mekanlar", "keywords": ["mutfak"], "search_volume": "low"},
            {"id": "banyo", "name": "Banyo", "category": "mekanlar", "keywords": ["banyo", "hamam"], "search_volume": "medium"},
            {"id": "tuvalet", "name": "Tuvalet", "category": "mekanlar", "keywords": ["tuvalet", "hela"], "search_volume": "high"},
            {"id": "yatak_odasi", "name": "Yatak Odası", "category": "mekanlar", "keywords": ["yatak odası"], "search_volume": "low"},
            {"id": "balkon", "name": "Balkon", "category": "mekanlar", "keywords": ["balkon", "teras"], "search_volume": "low"},
            {"id": "bahce", "name": "Bahçe", "category": "mekanlar", "keywords": ["bahçe"], "search_volume": "medium"},
            {"id": "cami", "name": "Cami", "category": "mekanlar", "keywords": ["cami", "mescit"], "search_volume": "high"},
            {"id": "kilise", "name": "Kilise", "category": "mekanlar", "keywords": ["kilise"], "search_volume": "low"},
            {"id": "mezarlik", "name": "Mezarlık", "category": "mekanlar", "keywords": ["mezarlık", "kabir", "türbe"], "search_volume": "high"},
            {"id": "hastane", "name": "Hastane", "category": "mekanlar", "keywords": ["hastane"], "search_volume": "medium"},
            {"id": "okul", "name": "Okul", "category": "mekanlar", "keywords": ["okul", "sınıf"], "search_volume": "medium"},
            {"id": "hapishane", "name": "Hapishane", "category": "mekanlar", "keywords": ["hapishane", "cezaevi"], "search_volume": "medium"},
            {"id": "saray", "name": "Saray", "category": "mekanlar", "keywords": ["saray"], "search_volume": "medium"},
            {"id": "kopru", "name": "Köprü", "category": "mekanlar", "keywords": ["köprü"], "search_volume": "medium"},
            {"id": "yol", "name": "Yol", "category": "mekanlar", "keywords": ["yol", "cadde", "sokak"], "search_volume": "medium"},
            {"id": "market", "name": "Market", "category": "mekanlar", "keywords": ["market", "mağaza"], "search_volume": "low"},
            {"id": "carsi", "name": "Çarşı", "category": "mekanlar", "keywords": ["çarşı", "pazar"], "search_volume": "low"},
            {"id": "otel", "name": "Otel", "category": "mekanlar", "keywords": ["otel"], "search_volume": "medium"},
            {"id": "asansor", "name": "Asansör", "category": "mekanlar", "keywords": ["asansör"], "search_volume": "medium"},
            {"id": "merdiven", "name": "Merdiven", "category": "mekanlar", "keywords": ["merdiven"], "search_volume": "high"},
            {"id": "bodrum", "name": "Bodrum", "category": "mekanlar", "keywords": ["bodrum", "kiler"], "search_volume": "medium"},
            {"id": "cati", "name": "Çatı", "category": "mekanlar", "keywords": ["çatı", "dam"], "search_volume": "medium"},
            {"id": "havaalani", "name": "Havaalanı", "category": "mekanlar", "keywords": ["havaalanı", "havalimanı"], "search_volume": "low"},
            {"id": "plaj", "name": "Plaj", "category": "mekanlar", "keywords": ["plaj", "sahil"], "search_volume": "medium"},
            {"id": "havuz", "name": "Havuz", "category": "mekanlar", "keywords": ["havuz", "yüzme havuzu"], "search_volume": "medium"},
            {"id": "is_yeri", "name": "İş Yeri", "category": "mekanlar", "keywords": ["iş yeri", "ofis"], "search_volume": "medium"},
            {"id": "fabrika", "name": "Fabrika", "category": "mekanlar", "keywords": ["fabrika"], "search_volume": "low"},

            # NESNELER (50+)
            {"id": "para", "name": "Para", "category": "nesneler", "keywords": ["para", "nakit", "banknot"], "search_volume": "high"},
            {"id": "altin", "name": "Altın", "category": "nesneler", "keywords": ["altın", "altın takı"], "search_volume": "high"},
            {"id": "gumus", "name": "Gümüş", "category": "nesneler", "keywords": ["gümüş"], "search_volume": "medium"},
            {"id": "elmas", "name": "Elmas", "category": "nesneler", "keywords": ["elmas", "pırlanta"], "search_volume": "medium"},
            {"id": "yuzuk", "name": "Yüzük", "category": "nesneler", "keywords": ["yüzük", "nişan yüzüğü", "alyans"], "search_volume": "high"},
            {"id": "bilezik", "name": "Bilezik", "category": "nesneler", "keywords": ["bilezik"], "search_volume": "medium"},
            {"id": "kolye", "name": "Kolye", "category": "nesneler", "keywords": ["kolye", "gerdanlık"], "search_volume": "medium"},
            {"id": "kupe", "name": "Küpe", "category": "nesneler", "keywords": ["küpe"], "search_volume": "medium"},
            {"id": "araba", "name": "Araba", "category": "nesneler", "keywords": ["araba", "otomobil", "araç"], "search_volume": "high"},
            {"id": "ucak", "name": "Uçak", "category": "nesneler", "keywords": ["uçak"], "search_volume": "medium"},
            {"id": "gemi", "name": "Gemi", "category": "nesneler", "keywords": ["gemi", "vapur", "tekne"], "search_volume": "medium"},
            {"id": "tren", "name": "Tren", "category": "nesneler", "keywords": ["tren"], "search_volume": "medium"},
            {"id": "bisiklet", "name": "Bisiklet", "category": "nesneler", "keywords": ["bisiklet"], "search_volume": "low"},
            {"id": "telefon", "name": "Telefon", "category": "nesneler", "keywords": ["telefon", "cep telefonu"], "search_volume": "medium"},
            {"id": "bilgisayar", "name": "Bilgisayar", "category": "nesneler", "keywords": ["bilgisayar"], "search_volume": "low"},
            {"id": "kitap", "name": "Kitap", "category": "nesneler", "keywords": ["kitap"], "search_volume": "medium"},
            {"id": "kalem", "name": "Kalem", "category": "nesneler", "keywords": ["kalem"], "search_volume": "low"},
            {"id": "bicak", "name": "Bıçak", "category": "nesneler", "keywords": ["bıçak"], "search_volume": "high"},
            {"id": "silah", "name": "Silah", "category": "nesneler", "keywords": ["silah", "tüfek", "tabanca"], "search_volume": "high"},
            {"id": "anahtar", "name": "Anahtar", "category": "nesneler", "keywords": ["anahtar"], "search_volume": "medium"},
            {"id": "kapi", "name": "Kapı", "category": "nesneler", "keywords": ["kapı"], "search_volume": "medium"},
            {"id": "pencere", "name": "Pencere", "category": "nesneler", "keywords": ["pencere", "cam"], "search_volume": "medium"},
            {"id": "ayna", "name": "Ayna", "category": "nesneler", "keywords": ["ayna"], "search_volume": "high"},
            {"id": "saat", "name": "Saat", "category": "nesneler", "keywords": ["saat", "kol saati"], "search_volume": "medium"},
            {"id": "yatak", "name": "Yatak", "category": "nesneler", "keywords": ["yatak", "döşek"], "search_volume": "medium"},
            {"id": "masa", "name": "Masa", "category": "nesneler", "keywords": ["masa"], "search_volume": "low"},
            {"id": "sandalye", "name": "Sandalye", "category": "nesneler", "keywords": ["sandalye", "koltuk"], "search_volume": "low"},
            {"id": "mum", "name": "Mum", "category": "nesneler", "keywords": ["mum"], "search_volume": "medium"},
            {"id": "tabut", "name": "Tabut", "category": "nesneler", "keywords": ["tabut", "cenaze"], "search_volume": "high"},
            {"id": "kefen", "name": "Kefen", "category": "nesneler", "keywords": ["kefen"], "search_volume": "medium"},
            {"id": "mezar", "name": "Mezar", "category": "nesneler", "keywords": ["mezar", "kabir"], "search_volume": "high"},
            {"id": "kuran", "name": "Kuran", "category": "nesneler", "keywords": ["kuran", "mushaf"], "search_volume": "high"},
            {"id": "tespih", "name": "Tespih", "category": "nesneler", "keywords": ["tespih"], "search_volume": "medium"},
            {"id": "bayrak", "name": "Bayrak", "category": "nesneler", "keywords": ["bayrak", "türk bayrağı"], "search_volume": "medium"},
            {"id": "ip", "name": "İp", "category": "nesneler", "keywords": ["ip", "halat", "urgan"], "search_volume": "medium"},
            {"id": "zincir", "name": "Zincir", "category": "nesneler", "keywords": ["zincir"], "search_volume": "medium"},
            {"id": "kilit", "name": "Kilit", "category": "nesneler", "keywords": ["kilit", "asma kilit"], "search_volume": "medium"},
            {"id": "canta", "name": "Çanta", "category": "nesneler", "keywords": ["çanta", "el çantası"], "search_volume": "medium"},
            {"id": "ayakkabi", "name": "Ayakkabı", "category": "nesneler", "keywords": ["ayakkabı", "terlik"], "search_volume": "high"},
            {"id": "elbise", "name": "Elbise", "category": "nesneler", "keywords": ["elbise", "kıyafet"], "search_volume": "medium"},
            {"id": "gelinlik", "name": "Gelinlik", "category": "nesneler", "keywords": ["gelinlik"], "search_volume": "high"},
            {"id": "basortusi", "name": "Başörtüsü", "category": "nesneler", "keywords": ["başörtüsü", "türban", "eşarp"], "search_volume": "medium"},
            {"id": "cuzdan", "name": "Cüzdan", "category": "nesneler", "keywords": ["cüzdan"], "search_volume": "medium"},
            {"id": "fotograf", "name": "Fotoğraf", "category": "nesneler", "keywords": ["fotoğraf", "resim"], "search_volume": "medium"},
            {"id": "mektup", "name": "Mektup", "category": "nesneler", "keywords": ["mektup"], "search_volume": "medium"},
            {"id": "hediye", "name": "Hediye", "category": "nesneler", "keywords": ["hediye"], "search_volume": "medium"},
            {"id": "bebek_arabasi", "name": "Bebek Arabası", "category": "nesneler", "keywords": ["bebek arabası"], "search_volume": "low"},
            {"id": "oyuncak", "name": "Oyuncak", "category": "nesneler", "keywords": ["oyuncak"], "search_volume": "low"},
            {"id": "besik", "name": "Beşik", "category": "nesneler", "keywords": ["beşik"], "search_volume": "low"},
            {"id": "supurge", "name": "Süpürge", "category": "nesneler", "keywords": ["süpürge"], "search_volume": "low"},

            # YİYECEK/İÇECEK (25+)
            {"id": "ekmek", "name": "Ekmek", "category": "yiyecekler", "keywords": ["ekmek"], "search_volume": "medium"},
            {"id": "et", "name": "Et", "category": "yiyecekler", "keywords": ["et", "kırmızı et"], "search_volume": "high"},
            {"id": "balik_yemek", "name": "Balık (Yemek)", "category": "yiyecekler", "keywords": ["balık yemek"], "search_volume": "medium"},
            {"id": "meyve", "name": "Meyve", "category": "yiyecekler", "keywords": ["meyve"], "search_volume": "medium"},
            {"id": "sut", "name": "Süt", "category": "yiyecekler", "keywords": ["süt"], "search_volume": "medium"},
            {"id": "peynir", "name": "Peynir", "category": "yiyecekler", "keywords": ["peynir"], "search_volume": "low"},
            {"id": "yumurta", "name": "Yumurta", "category": "yiyecekler", "keywords": ["yumurta"], "search_volume": "medium"},
            {"id": "bal", "name": "Bal", "category": "yiyecekler", "keywords": ["bal"], "search_volume": "medium"},
            {"id": "seker", "name": "Şeker", "category": "yiyecekler", "keywords": ["şeker"], "search_volume": "low"},
            {"id": "tuz", "name": "Tuz", "category": "yiyecekler", "keywords": ["tuz"], "search_volume": "low"},
            {"id": "elma", "name": "Elma", "category": "yiyecekler", "keywords": ["elma"], "search_volume": "medium"},
            {"id": "uzum", "name": "Üzüm", "category": "yiyecekler", "keywords": ["üzüm"], "search_volume": "medium"},
            {"id": "nar", "name": "Nar", "category": "yiyecekler", "keywords": ["nar"], "search_volume": "medium"},
            {"id": "incir", "name": "İncir", "category": "yiyecekler", "keywords": ["incir"], "search_volume": "medium"},
            {"id": "hurma", "name": "Hurma", "category": "yiyecekler", "keywords": ["hurma"], "search_volume": "medium"},
            {"id": "zeytin", "name": "Zeytin", "category": "yiyecekler", "keywords": ["zeytin"], "search_volume": "low"},
            {"id": "cay", "name": "Çay", "category": "yiyecekler", "keywords": ["çay"], "search_volume": "medium"},
            {"id": "kahve", "name": "Kahve", "category": "yiyecekler", "keywords": ["kahve", "türk kahvesi"], "search_volume": "medium"},
            {"id": "sarap", "name": "Şarap", "category": "yiyecekler", "keywords": ["şarap", "içki"], "search_volume": "medium"},
            {"id": "raki", "name": "Rakı", "category": "yiyecekler", "keywords": ["rakı", "alkol"], "search_volume": "medium"},
            {"id": "bira", "name": "Bira", "category": "yiyecekler", "keywords": ["bira"], "search_volume": "medium"},
            {"id": "tatli", "name": "Tatlı", "category": "yiyecekler", "keywords": ["tatlı", "baklava", "pasta"], "search_volume": "medium"},
            {"id": "dondurma", "name": "Dondurma", "category": "yiyecekler", "keywords": ["dondurma"], "search_volume": "low"},
            {"id": "cikolata", "name": "Çikolata", "category": "yiyecekler", "keywords": ["çikolata"], "search_volume": "low"},
            {"id": "pilav", "name": "Pilav", "category": "yiyecekler", "keywords": ["pilav"], "search_volume": "low"},

            # VÜCUT (25+)
            {"id": "sac", "name": "Saç", "category": "vucut", "keywords": ["saç", "saçlar"], "search_volume": "high"},
            {"id": "sac_dokulmesi", "name": "Saç Dökülmesi", "category": "vucut", "keywords": ["saç dökülmesi", "kel"], "search_volume": "medium"},
            {"id": "goz", "name": "Göz", "category": "vucut", "keywords": ["göz", "gözler"], "search_volume": "medium"},
            {"id": "kulak", "name": "Kulak", "category": "vucut", "keywords": ["kulak"], "search_volume": "low"},
            {"id": "burun", "name": "Burun", "category": "vucut", "keywords": ["burun"], "search_volume": "low"},
            {"id": "agiz", "name": "Ağız", "category": "vucut", "keywords": ["ağız"], "search_volume": "low"},
            {"id": "dis", "name": "Diş", "category": "vucut", "keywords": ["diş", "dişler"], "search_volume": "high"},
            {"id": "dis_dusmesi", "name": "Diş Düşmesi", "category": "vucut", "keywords": ["diş düşmesi", "diş kırılması"], "search_volume": "high"},
            {"id": "dil", "name": "Dil", "category": "vucut", "keywords": ["dil"], "search_volume": "low"},
            {"id": "el", "name": "El", "category": "vucut", "keywords": ["el", "eller"], "search_volume": "medium"},
            {"id": "ayak", "name": "Ayak", "category": "vucut", "keywords": ["ayak", "ayaklar"], "search_volume": "medium"},
            {"id": "parmak", "name": "Parmak", "category": "vucut", "keywords": ["parmak"], "search_volume": "medium"},
            {"id": "tirnak", "name": "Tırnak", "category": "vucut", "keywords": ["tırnak"], "search_volume": "medium"},
            {"id": "kan", "name": "Kan", "category": "vucut", "keywords": ["kan"], "search_volume": "high"},
            {"id": "gozyasi", "name": "Gözyaşı", "category": "vucut", "keywords": ["gözyaşı"], "search_volume": "medium"},
            {"id": "bas", "name": "Baş", "category": "vucut", "keywords": ["baş", "kafa"], "search_volume": "medium"},
            {"id": "yuz", "name": "Yüz", "category": "vucut", "keywords": ["yüz", "surat"], "search_volume": "medium"},
            {"id": "kalp", "name": "Kalp", "category": "vucut", "keywords": ["kalp", "yürek"], "search_volume": "medium"},
            {"id": "beyin", "name": "Beyin", "category": "vucut", "keywords": ["beyin", "akıl"], "search_volume": "low"},
            {"id": "kemik", "name": "Kemik", "category": "vucut", "keywords": ["kemik"], "search_volume": "medium"},
            {"id": "idrar", "name": "İdrar", "category": "vucut", "keywords": ["idrar", "işemek", "çiş"], "search_volume": "medium"},
            {"id": "diski", "name": "Dışkı", "category": "vucut", "keywords": ["dışkı", "kaka", "pislik"], "search_volume": "high"},
            {"id": "kusma", "name": "Kusma", "category": "vucut", "keywords": ["kusma", "kusmak"], "search_volume": "medium"},
            {"id": "hamilelik", "name": "Hamilelik", "category": "vucut", "keywords": ["hamilelik", "gebelik"], "search_volume": "high"},
            {"id": "adet_gormek", "name": "Adet Görmek", "category": "vucut", "keywords": ["adet", "regl", "aybaşı"], "search_volume": "high"},

            # DURUMLAR / EYLEMLER (35+)
            {"id": "olum", "name": "Ölüm", "category": "durumlar", "keywords": ["ölüm", "ölmek", "vefat"], "search_volume": "high"},
            {"id": "dogum", "name": "Doğum", "category": "durumlar", "keywords": ["doğum", "doğurmak"], "search_volume": "high"},
            {"id": "evlilik", "name": "Evlilik", "category": "durumlar", "keywords": ["evlilik", "evlenmek", "düğün", "nikah"], "search_volume": "high"},
            {"id": "bosanma", "name": "Boşanma", "category": "durumlar", "keywords": ["boşanma", "boşanmak", "ayrılık"], "search_volume": "medium"},
            {"id": "kavga", "name": "Kavga", "category": "durumlar", "keywords": ["kavga", "dövüş", "tartışma"], "search_volume": "high"},
            {"id": "kaza", "name": "Kaza", "category": "durumlar", "keywords": ["kaza", "trafik kazası"], "search_volume": "medium"},
            {"id": "hastalik", "name": "Hastalık", "category": "durumlar", "keywords": ["hastalık", "hasta olmak"], "search_volume": "medium"},
            {"id": "ucmak", "name": "Uçmak", "category": "durumlar", "keywords": ["uçmak", "uçma", "havada uçmak"], "search_volume": "high"},
            {"id": "dusmek", "name": "Düşmek", "category": "durumlar", "keywords": ["düşmek", "düşme", "yüksekten düşmek"], "search_volume": "high"},
            {"id": "yuzmek", "name": "Yüzmek", "category": "durumlar", "keywords": ["yüzmek", "yüzme"], "search_volume": "medium"},
            {"id": "bogulmak", "name": "Boğulmak", "category": "durumlar", "keywords": ["boğulmak", "boğulma"], "search_volume": "high"},
            {"id": "kosmak", "name": "Koşmak", "category": "durumlar", "keywords": ["koşmak", "koşma"], "search_volume": "medium"},
            {"id": "kacmak", "name": "Kaçmak", "category": "durumlar", "keywords": ["kaçmak", "kaçış"], "search_volume": "medium"},
            {"id": "kovalanmak", "name": "Kovalanmak", "category": "durumlar", "keywords": ["kovalanmak", "takip edilmek"], "search_volume": "high"},
            {"id": "kaybolmak", "name": "Kaybolmak", "category": "durumlar", "keywords": ["kaybolmak", "kayıp"], "search_volume": "medium"},
            {"id": "ciplaklik", "name": "Çıplaklık", "category": "durumlar", "keywords": ["çıplak", "çıplaklık"], "search_volume": "high"},
            {"id": "cinsel_iliski", "name": "Cinsel İlişki", "category": "durumlar", "keywords": ["cinsel ilişki", "seks"], "search_volume": "high"},
            {"id": "opusmek", "name": "Öpüşmek", "category": "durumlar", "keywords": ["öpüşmek", "öpmek", "öpücük"], "search_volume": "medium"},
            {"id": "sarilmak", "name": "Sarılmak", "category": "durumlar", "keywords": ["sarılmak", "kucaklaşmak"], "search_volume": "medium"},
            {"id": "aglamak", "name": "Ağlamak", "category": "durumlar", "keywords": ["ağlamak", "ağlama"], "search_volume": "high"},
            {"id": "gulmek", "name": "Gülmek", "category": "durumlar", "keywords": ["gülmek", "gülme", "kahkaha"], "search_volume": "medium"},
            {"id": "namaz_kilmak", "name": "Namaz Kılmak", "category": "durumlar", "keywords": ["namaz", "namaz kılmak"], "search_volume": "high"},
            {"id": "ezan", "name": "Ezan", "category": "durumlar", "keywords": ["ezan", "ezan sesi"], "search_volume": "medium"},
            {"id": "abdest", "name": "Abdest", "category": "durumlar", "keywords": ["abdest", "abdest almak"], "search_volume": "medium"},
            {"id": "hac", "name": "Hac", "category": "durumlar", "keywords": ["hac", "hacca gitmek", "kabe"], "search_volume": "medium"},
            {"id": "cenaze", "name": "Cenaze", "category": "durumlar", "keywords": ["cenaze", "cenaze namazı"], "search_volume": "high"},
            {"id": "sinav", "name": "Sınav", "category": "durumlar", "keywords": ["sınav", "imtihan", "test"], "search_volume": "medium"},
            {"id": "piyango", "name": "Piyango", "category": "durumlar", "keywords": ["piyango", "kazanmak"], "search_volume": "medium"},
            {"id": "hirsizlik", "name": "Hırsızlık", "category": "durumlar", "keywords": ["hırsızlık", "soygun"], "search_volume": "medium"},
            {"id": "yangin", "name": "Yangın", "category": "durumlar", "keywords": ["yangın", "yanmak"], "search_volume": "high"},
            {"id": "sarhos_olmak", "name": "Sarhoş Olmak", "category": "durumlar", "keywords": ["sarhoş", "sarhoş olmak"], "search_volume": "medium"},
            {"id": "sigara_icmek", "name": "Sigara İçmek", "category": "durumlar", "keywords": ["sigara", "sigara içmek"], "search_volume": "medium"},
            {"id": "gec_kalmak", "name": "Geç Kalmak", "category": "durumlar", "keywords": ["geç kalmak"], "search_volume": "medium"},
            {"id": "yolculuk", "name": "Yolculuk", "category": "durumlar", "keywords": ["yolculuk", "seyahat"], "search_volume": "medium"},
            {"id": "tasinmak", "name": "Taşınmak", "category": "durumlar", "keywords": ["taşınmak", "ev taşımak"], "search_volume": "low"},

            # DİNİ/MANEVİ (15+)
            {"id": "allah", "name": "Allah", "category": "dini", "keywords": ["allah", "tanrı"], "search_volume": "high"},
            {"id": "peygamber", "name": "Peygamber", "category": "dini", "keywords": ["peygamber", "hz. muhammed", "resulullah"], "search_volume": "high"},
            {"id": "melek", "name": "Melek", "category": "dini", "keywords": ["melek", "melekler"], "search_volume": "high"},
            {"id": "seytan", "name": "Şeytan", "category": "dini", "keywords": ["şeytan", "iblis"], "search_volume": "high"},
            {"id": "cin", "name": "Cin", "category": "dini", "keywords": ["cin", "cinler"], "search_volume": "high"},
            {"id": "kabe", "name": "Kabe", "category": "dini", "keywords": ["kabe", "beytullah"], "search_volume": "medium"},
            {"id": "cennet", "name": "Cennet", "category": "dini", "keywords": ["cennet"], "search_volume": "medium"},
            {"id": "cehennem", "name": "Cehennem", "category": "dini", "keywords": ["cehennem"], "search_volume": "medium"},
            {"id": "kiyamet", "name": "Kıyamet", "category": "dini", "keywords": ["kıyamet", "mahşer"], "search_volume": "medium"},
            {"id": "sela", "name": "Sela", "category": "dini", "keywords": ["sela", "sela sesi"], "search_volume": "medium"},
            {"id": "cami_imam", "name": "Cami ve İmam", "category": "dini", "keywords": ["cami", "imam"], "search_volume": "medium"},
            {"id": "kurban", "name": "Kurban", "category": "dini", "keywords": ["kurban", "kurban kesmek"], "search_volume": "medium"},
            {"id": "zekat", "name": "Zekat", "category": "dini", "keywords": ["zekat", "sadaka"], "search_volume": "low"},
            {"id": "oruc", "name": "Oruç", "category": "dini", "keywords": ["oruç", "oruç tutmak"], "search_volume": "medium"},
            {"id": "ramazan", "name": "Ramazan", "category": "dini", "keywords": ["ramazan", "iftar"], "search_volume": "medium"},

            # RENKLER (10)
            {"id": "beyaz", "name": "Beyaz Renk", "category": "renkler", "keywords": ["beyaz", "beyaz renk"], "search_volume": "medium"},
            {"id": "siyah", "name": "Siyah Renk", "category": "renkler", "keywords": ["siyah", "siyah renk", "kara"], "search_volume": "medium"},
            {"id": "kirmizi", "name": "Kırmızı Renk", "category": "renkler", "keywords": ["kırmızı", "kızıl", "al"], "search_volume": "medium"},
            {"id": "mavi", "name": "Mavi Renk", "category": "renkler", "keywords": ["mavi", "gök mavisi"], "search_volume": "low"},
            {"id": "yesil", "name": "Yeşil Renk", "category": "renkler", "keywords": ["yeşil"], "search_volume": "medium"},
            {"id": "sari", "name": "Sarı Renk", "category": "renkler", "keywords": ["sarı"], "search_volume": "low"},
            {"id": "mor", "name": "Mor Renk", "category": "renkler", "keywords": ["mor"], "search_volume": "low"},
            {"id": "turuncu", "name": "Turuncu Renk", "category": "renkler", "keywords": ["turuncu"], "search_volume": "low"},
            {"id": "pembe", "name": "Pembe Renk", "category": "renkler", "keywords": ["pembe"], "search_volume": "low"},
            {"id": "altin_rengi", "name": "Altın Rengi", "category": "renkler", "keywords": ["altın rengi", "gold"], "search_volume": "low"},
        ]

        return objects

    def generate_actions(self):
        """Eylemler listesi"""
        actions = [
            {"id": "gormek", "name": "görmek"},
            {"id": "oldurmek", "name": "öldürmek"},
            {"id": "oldurulmek", "name": "öldürülmek"},
            {"id": "kacmak", "name": "kaçmak"},
            {"id": "kovalamak", "name": "kovalamak"},
            {"id": "yakalamak", "name": "yakalamak"},
            {"id": "yemek", "name": "yemek"},
            {"id": "icmek", "name": "içmek"},
            {"id": "konusmak", "name": "konuşmak"},
            {"id": "sarilmak", "name": "sarılmak"},
            {"id": "opmek", "name": "öpmek"},
            {"id": "kavga_etmek", "name": "kavga etmek"},
            {"id": "dovmek", "name": "dövmek"},
            {"id": "dovulmek", "name": "dövülmek"},
            {"id": "aglamak", "name": "ağlamak"},
            {"id": "gulmek", "name": "gülmek"},
            {"id": "korkmak", "name": "korkmak"},
            {"id": "ucmak", "name": "uçmak"},
            {"id": "dusmek", "name": "düşmek"},
            {"id": "yuzmek", "name": "yüzmek"},
            {"id": "bogulmak", "name": "boğulmak"},
            {"id": "kosmak", "name": "koşmak"},
            {"id": "binmek", "name": "binmek"},
            {"id": "almak", "name": "almak"},
            {"id": "vermek", "name": "vermek"},
            {"id": "kaybetmek", "name": "kaybetmek"},
            {"id": "bulmak", "name": "bulmak"},
            {"id": "isirmak", "name": "ısırmak"},
            {"id": "isirilmak", "name": "ısırılmak"},
            {"id": "sokmak", "name": "sokmak"},
        ]
        return actions

    def save_data(self):
        """Tüm verileri kaydet"""

        objects = self.generate_objects()
        with open(self.data_dir / "objects.json", "w", encoding="utf-8") as f:
            json.dump({"objects": objects}, f, ensure_ascii=False, indent=2)
        print(f"✅ {len(objects)} obje kaydedildi: data/raw/objects.json")

        actions = self.generate_actions()
        with open(self.data_dir / "actions.json", "w", encoding="utf-8") as f:
            json.dump({"actions": actions}, f, ensure_ascii=False, indent=2)
        print(f"✅ {len(actions)} eylem kaydedildi: data/raw/actions.json")

if __name__ == "__main__":
    collector = DataCollector()
    collector.save_data()
